experiment_name: 'attr__loss_cosine__sample_all_values_unigram__sample_attr_values_uniform'


data:
    img_dir: "/mnt/hd1/mumie-img"
    train_dir: "/mnt/hd1/mumie-json/final/train"
    val_dir: "/mnt/hd1/mumie-json/final/val-mini"
    test_dir: "/mnt/hd1/mumie-json/final/test"
    desc_file: "data/desc.txt"
    attr_file: "data/attr.txt"
    value_file: "data/value.txt"
    vgg_ckpt: "data/ckpt/vgg/vgg_16.ckpt"
    glove_ckpt: "data/ckpt/glove/glove.ckpt"
    attr_vocab_size: 2114
    value_vocab_size: 15380
    desc_vocab_size: 100000


model:
    use_tables: False
    use_images: False
    use_descs: False

    embedding_size: 200
    fusion_method:

    table_encoder_params:
    image_encoder_params:
    desc_encoder_params:


training:
    batch_size: 16
    ckpt_dir: "data/ckpt"
    gradient_clipping: 1.0
    log_dir: "data/log"
    log_frequency: 100
    learning_rate: 0.00001
    max_desc_length: 1000
    max_number_of_images: 4
    max_steps: 1500000
    neg_sample_from_all_values: True
    neg_sample_from_attr_values: True
    neg_sample_unk: False
    pos_sample_unk: False
    random_seed: 1337
    sampling_method: "unigram"
    save_frequency: 10000

