experiment_name: 'av__clean__1024__cosine__no_unk'


data:
    img_dir: "/mnt/hd1/mumie-img"
    train_dir: "/mnt/hd1/mumie-json/final-cleaned/train"
    val_dir: "/mnt/hd1/mumie-json/final-cleaned/val-mini"
    test_dir: "/mnt/hd1/mumie-json/final-cleaned/test"
    desc_file: "data/clean/desc.txt"
    attr_file: "data/clean/attr.txt"
    value_file: "data/clean/value.txt"
    attr_vocab_size: 1502
    value_vocab_size: 8662
    desc_vocab_size: 458085


model:
    use_tables: False
    use_images: False
    use_descs: False

    embedding_size: 1024
    fusion_method:
    distance_metric: "cosine"

    table_encoder_params:
    image_encoder_params:
    desc_encoder_params:


training:
    batch_size: 128
    ckpt_dir: "data/ckpt"
    gradient_clipping: 1.0
    log_dir: "data/log"
    log_frequency: 100
    learning_rate: 0.000005
    max_desc_length:
    max_number_of_images: 4
    max_steps: 1000000
    neg_sample_from_all_values: True
    neg_sample_from_attr_values: False
    neg_sample_unk: True
    pos_sample_unk: False
    random_seed: 1337
    sampling_method: "uniform"
    save_frequency: 1000

