experiment_name: "title__normalized__logit__gru"


data:
    img_dir: "/mnt/hd1/mumie-img"
    train_dir: "/mnt/hd1/mumie-json/normalized_no_tables/train"
    val_dir: "/mnt/hd1/mumie-json/normalized_no_tables/val"
    val_gold_dir: "/mnt/hd1/mumie-json/normalized_no_tables/val-gold"
    desc_file: "data/normalized_no_tables/desc.txt"
    attr_file: "data/normalized_no_tables/attr.txt"
    value_file: "data/normalized_no_tables/value.txt"
    image_encoder_ckpt: "./data/ckpt/vgg/vgg_16.ckpt"
    # image_encoder_ckpt: "./data/ckpt/inception_v3/inception_v3.ckpt"
    image_encoder_scope: "vgg_16/conv"
    # image_encoder_scope: "InceptionV3"
    glove_ckpt: "./data/ckpt/glove_normalized_no_tables/embeddings.ckpt"
    av_ckpt:
    attr_vocab_size: 835
    value_vocab_size: 3094 # Remember: +1 for UNK (if using UNK)
    desc_vocab_size: 199361


model:
    use_tables: False
    use_images: False
    use_descs: False
    use_titles: True

    trainable_attr_embeddings: True
    trainable_value_embeddings: True
    trainable_word_embeddings: False
    trainable_image_encoder_weights: False

    word_embedding_size: 200
    context_embedding_size: 2048
    fusion_method: "concat"

    mae_params:
        n_hidden: 1
        hidden_size: 4096
        attr_gating: False

    table_encoder_params:
        num_outputs: 2048
        dropout_keep_prob: 0.90
        phi_layers: 3
        phi_units: 2048
        rho_layers: 3
        rho_units: 2048

    image_encoder_params:
        num_outputs: 2048
        dropout_keep_prob: 0.9
        use_attention: False
        architecture: "vgg"

    desc_encoder_params:
        num_outputs: 2048
        dropout_keep_prob: 0.9
        window_sizes: [5,7]
        num_filters: 512
        fusion: "late"
        architecture: "cnn_desc_encoder"

    title_encoder_params:
        num_outputs: 2048
        dropout_keep_prob: 0.9
        num_layers: 2
        hidden_size: 512
        fusion: "late"
        architecture: "gru_desc_encoder"


training:
    batch_size: 32
    ckpt_dir: "data/ckpt"
    decay_steps: 100000
    decay_rate: 0.32
    gradient_clipping: 0.5
    initial_learning_rate: 0.0003
    log_dir: "data/log"
    log_frequency: 100
    max_desc_length: 1000
    max_number_of_images: 4
    max_steps: 300000
    random_seed: 1337
    save_frequency: 25000

