experiment_name: "desc_title__normalized__new_metrics_test"


data:
    img_dir: "/mnt/hd1/mumie-img"
    train_dir: "/mnt/hd1/mumie-json/normalized_no_tables/train"
    val_dir: "/mnt/hd1/mumie-json/normalized_no_tables/val-mini"
    val_gold_dir: "/mnt/hd1/mumie-json/normalized_no_tables/val-gold"
    desc_file: "data/normalized_no_tables/desc.txt"
    attr_file: "data/normalized_no_tables/attr.txt"
    value_file: "data/normalized_no_tables/value.txt"
    vgg_ckpt: "./data/ckpt/vgg/vgg_16.ckpt"
    glove_ckpt: "./data/ckpt/glove_normalized_no_tables/embeddings.ckpt"
    av_ckpt:
    attr_vocab_size: 835
    value_vocab_size: 3094 # Remember: +1 for UNK (if using UNK)
    desc_vocab_size: 199361


model:
    use_tables: False
    use_images: False
    use_descs: True
    use_titles: True

    trainable_attr_embeddings: True
    trainable_value_embeddings: True
    trainable_word_embeddings: False

    word_embedding_size: 200
    context_embedding_size: 1024
    fusion_method: "concat"
    distance_metric: "cosine"

    table_encoder_params:
        num_outputs: 2048
        dropout_keep_prob: 0.90
        phi_layers: 3
        phi_units: 2048
        rho_layers: 3
        rho_units: 2048

    image_encoder_params:
        num_outputs: 1024
        dropout_keep_prob: 0.50
        use_attention: False

    desc_encoder_params:
        num_outputs: 1024
        dropout_keep_prob: 0.90
        window_sizes: [5,7]
        num_filters: 1024
        fusion: "late"

    title_encoder_params:
        num_outputs: 1024
        dropout_keep_prob: 0.90
        window_sizes: [5,7]
        num_filters: 1024
        fusion: "late"

training:
    batch_size: 32
    ckpt_dir: "data/ckpt"
    decay_steps: 100000
    decay_rate: 0.50
    gradient_clipping: 0.5
    initial_learning_rate: 0.0003
    log_dir: "data/log"
    log_frequency: 100
    max_desc_length: 1000
    max_number_of_images: 4
    max_steps: 10000000
    neg_sample_from_all_values: True
    neg_sample_from_attr_values: True
    neg_sample_unk: False
    pos_sample_unk: False
    random_seed: 1337
    sampling_method: "unigram"
    save_frequency: 1000

