experiment_name: "multiclass_attr__desc__no_tables"


data:
    img_dir: "/mnt/hd1/mumie-img"
    train_dir: "/mnt/hd1/mumie-json/no_tables/train"
    val_dir: "/mnt/hd1/mumie-json/no_tables/val-mini"
    test_dir: "/mnt/hd1/mumie-json/no_tables/test"
    desc_file: "data/no_tables/desc.txt"
    attr_file: "data/no_tables/attr.txt"
    value_file: "data/no_tables/value.txt"
    vgg_ckpt: "./data/ckpt/vgg/vgg_16.ckpt"
    glove_ckpt: "./data/ckpt/glove_no_tables/embeddings.ckpt"
    attr_vocab_size: 947
    value_vocab_size: 4429 # Remember: +1 for UNK (if using UNK)
    desc_vocab_size: 185722


model:
    use_images: False
    use_descs: True

    trainable_word_embeddings: False

    word_embedding_size: 200
    context_embedding_size: 512

    image_encoder_params:
        num_outputs: 2048
        dropout_keep_prob: 0.50
        use_attention: False

    desc_encoder_params:
        num_outputs: 1024
        dropout_keep_prob: 0.50
        window_sizes: [3,5,7,9]
        num_filters: 1024
        fusion: "late"


training:
    batch_size: 32
    ckpt_dir: "data/ckpt"
    decay_steps: 100000
    decay_rate: 0.10
    gradient_clipping: 0.5
    initial_learning_rate: 0.0003
    log_dir: "data/log"
    log_frequency: 100
    max_desc_length: 1000
    max_number_of_images: 4
    max_steps: 500000
    random_seed: 1337
    save_frequency: 10000

