experiment_name: 'euclidean__embeddings__mapped__4096'


data:
    img_dir: "/mnt/hd1/mumie-img"
    train_dir: "/mnt/hd1/mumie-json/final-cleaned/train"
    val_dir: "/mnt/hd1/mumie-json/final-cleaned/val-mini"
    test_dir: "/mnt/hd1/mumie-json/final-cleaned/test"
    desc_file: "data/mapped/desc.txt"
    attr_file: "data/mapped/attr.txt"
    value_file: "data/mapped/value.txt"
    attr_vocab_size: 1511
    value_vocab_size: 10471
    desc_vocab_size: 552289


model:
    use_tables: False
    use_images: False
    use_descs: False

    embedding_size: 4096
    fusion_method:
    distance_metric: "euclidean"

    table_encoder_params:
    image_encoder_params:
    desc_encoder_params:


training:
    batch_size: 128
    ckpt_dir: "data/ckpt"
    gradient_clipping: 1.0
    log_dir: "data/log"
    log_frequency: 100
    learning_rate: 0.00005
    max_desc_length:
    max_number_of_images: 4
    max_steps: 1000000
    neg_sample_from_all_values: True
    neg_sample_from_attr_values: True
    neg_sample_unk: True
    pos_sample_unk: True
    random_seed: 1337
    sampling_method: "unigram"
    save_frequency: 1000

